### ISSUE TITLE
CUDA OOM on 3090 GPU

### ISSUE THREAD

**Issue by CalvinPaean** [aigc3d/LHM#103]
When I run the following scripts in shell on Ubuntu22 OS with a single 3090 GPU,

```bash
# Memory-saving version; More time available for Use.
# The maximum supported length for 720P video is 20s.
python ./app_motion_ms.py  
python ./app_motion_ms.py  --model_name LHM-MINI


# Support user motion sequence input. As the pose estimator requires some GPU memory, this Gradio application requires at least 24 GB of GPU memory to run LHM-500M.
python ./app_motion.py  
python ./app_motion.py  --model_name LHM-MINI

# preprocessing video sequence
python ./app.py
python ./app.py --model_name LHM-MINI
```

I got this error:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 67371012.02 GiB.

Could you please help me solve this problem?

**Comment by lingtengqiu** [comment]
I suspect that this issue is related to the version of the library. The memory you are attempting to allocate is (67,371,012.02 GiB), which is so large that no device can run this task. Please check the version of the dependent library.

**Comment by CalvinPaean** [comment]
> I suspect that this issue is related to the version of the library. The memory you are attempting to allocate is (67,371,012.02 GiB), which is so large that no device can run this task. Please check the version of the dependent library.

Thanks a lot for your reply :). But I simply used the docker environment you provided in README.md,

```bash
wget -P ./lhm_cuda_dockers https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/aigc3d/data/for_lingteng/LHM/LHM_Docker/lhm_cuda121.tar 
```

**Comment by CalvinPaean** [comment]
Thanks a lot. I have solved this issue. Because in the docker environment, I have to install the package `diff-gaussian-rasterization` by the following commands:

```bash
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
```

**Comment by CalvinPaean** [comment]
> I suspect that this issue is related to the version of the library. The memory you are attempting to allocate is (67,371,012.02 GiB), which is so large that no device can run this task. Please check the version of the dependent library.

Thanks a lot. I have solved this issue. Because in the docker environment, I have to install the package `diff-gaussian-rasterization` by the following commands:

```bash
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
```

**Comment by ops120** [comment]
> > 我怀疑这个问题与库的版本有关。您尝试分配的内存为 67,371,012.02 GiB，这太大了，以至于没有设备可以运行此任务。请检查依赖库的版本。
> 
> `diff-gaussian-rasterization`非常感谢。我已经解决了这个问题。因为在docker环境中，我必须通过以下命令安装软件包：
> 
> git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
> pip install ./diff-gaussian-rasterization

搞定，帮我未来的我
