### ISSUE TITLE
Unknown Issue: Gets stuck or hangs?

### ISSUE THREAD

**Issue by Deathdadev** [aigc3d/LHM#15]
Here is the console after running the inference script, but it is taking forever with no progress:
```
TRAIN_CONFIG: .\configs\inference\human-lrm-1B.yaml
IMAGE_INPUT: .\train_data\example_imgs\
MODEL_NAME: LHM-1B
MOTION_SEQS_DIR: .\train_data\motion_video\mimo6\smplx_params\
INFERENCE VIDEO
[896]
Loading model...
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
[2025-03-22 19:23:28,652] LHM.models.modeling_human_lrm: [INFO] Using Dinov2FusionWrapper as the encoder
INFO:LHM.models.modeling_human_lrm:Using Dinov2FusionWrapper as the encoder
C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
==========skip_decoder:True
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
  warnings.warn(error_message)
load voxel_grid voxel_192.pth
<All keys matched successfully>
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
[2025-03-22 19:23:45,904] LHM.models.modeling_human_lrm: [INFO] Using Sapiens as the encoder
INFO:LHM.models.modeling_human_lrm:Using Sapiens as the encoder
[2025-03-22 19:23:52,520] LHM.models.encoders.sapiens_warpper: [WARNING] ======== Freezing Sapiens Model ========
WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
Loading weights from local directory
  0%|                                                                                            | 0/9 [00:00<?, ?it/s]subdir_path and uid: .\train_data\example_imgs -00000000_joker_2
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
BiRefNet is ready to use.
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  x = F.scaled_dot_product_attention(
C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\nn\modules\module.py:1541: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return forward_call(*args, **kwargs)
```

The interface sometimes just doesnt start, so I have to run app.py again, and then the same issue occurs with it seemingly not doing anything
```
python app.py
[896]
Loading model...
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
==========skip_decoder:True
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
  warnings.warn(error_message)
load voxel_grid voxel_192.pth
<All keys matched successfully>
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
Loading weights from local directory
(lhm) PS C:\Users\User\documents\github\lhm> python app.py
[896]
Loading model...
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
==========skip_decoder:True
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
  warnings.warn(error_message)
load voxel_grid voxel_192.pth
<All keys matched successfully>
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
Loading weights from local directory
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
subdir_path and uid:  raw
C:\Users\User\AppData\Local\Temp\tmpl63d85c0\raw.png ./train_data/motion_video/nezha\smplx_params C:\Users\User\AppData\Local\Temp\tmpl63d85c0 C:\Users\User\AppData\Local\Temp\tmpl63d85c0\output.mp4
BiRefNet is ready to use.
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  x = F.scaled_dot_product_attention(
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\nn\modules\module.py:1541: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return forward_call(*args, **kwargs)
```

**Comment by lingtengqiu** [comment]
Currently, We only test on the Linux System :(. we will test how to run successfully on Windows, next week.

**Comment by lingtengqiu** [comment]
> Here is the console after running the inference script, but it is taking forever with no progress:
> 
> ```
> TRAIN_CONFIG: .\configs\inference\human-lrm-1B.yaml
> IMAGE_INPUT: .\train_data\example_imgs\
> MODEL_NAME: LHM-1B
> MOTION_SEQS_DIR: .\train_data\motion_video\mimo6\smplx_params\
> INFERENCE VIDEO
> [896]
> Loading model...
> A matching Triton is not available, some optimizations will not be enabled
> Traceback (most recent call last):
>   File "C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
>     from xformers.triton.softmax import softmax as triton_softmax  # noqa
>   File "C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
>     import triton
> ModuleNotFoundError: No module named 'triton'
> C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\Documents\github\LHM\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> person center is head
> Model loaded
> [2025-03-22 19:23:28,652] LHM.models.modeling_human_lrm: [INFO] Using Dinov2FusionWrapper as the encoder
> INFO:LHM.models.modeling_human_lrm:Using Dinov2FusionWrapper as the encoder
> C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\Documents\github\LHM\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> ==========skip_decoder:True
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
> CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
>   warnings.warn(error_message)
> load voxel_grid voxel_192.pth
> <All keys matched successfully>
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
>   warnings.warn(
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
>   warnings.warn(msg)
> [2025-03-22 19:23:45,904] LHM.models.modeling_human_lrm: [INFO] Using Sapiens as the encoder
> INFO:LHM.models.modeling_human_lrm:Using Sapiens as the encoder
> [2025-03-22 19:23:52,520] LHM.models.encoders.sapiens_warpper: [WARNING] ======== Freezing Sapiens Model ========
> WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
> Loading weights from local directory
>   0%|                                                                                            | 0/9 [00:00<?, ?it/s]subdir_path and uid: .\train_data\example_imgs -00000000_joker_2
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
>   return F.conv2d(input, weight, bias, self.stride,
> BiRefNet is ready to use.
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
>   x = F.scaled_dot_product_attention(
> C:\Users\User\Documents\github\LHM\.venv\lib\site-packages\torch\nn\modules\module.py:1541: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
>   return forward_call(*args, **kwargs)
> ```
> 
> The interface sometimes just doesnt start, so I have to run app.py again, and then the same issue occurs with it seemingly not doing anything
> 
> ```
> python app.py
> [896]
> Loading model...
> A matching Triton is not available, some optimizations will not be enabled
> Traceback (most recent call last):
>   File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
>     from xformers.triton.softmax import softmax as triton_softmax  # noqa
>   File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
>     import triton
> ModuleNotFoundError: No module named 'triton'
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> person center is head
> Model loaded
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> ==========skip_decoder:True
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
> CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
>   warnings.warn(error_message)
> load voxel_grid voxel_192.pth
> <All keys matched successfully>
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
>   warnings.warn(
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
>   warnings.warn(msg)
> WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
> Loading weights from local directory
> (lhm) PS C:\Users\User\documents\github\lhm> python app.py
> [896]
> Loading model...
> A matching Triton is not available, some optimizations will not be enabled
> Traceback (most recent call last):
>   File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
>     from xformers.triton.softmax import softmax as triton_softmax  # noqa
>   File "C:\Users\User\documents\github\lhm\.venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
>     import triton
> ModuleNotFoundError: No module named 'triton'
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\documents\github\lhm\./engine/pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> person center is head
> Model loaded
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
>   warnings.warn("xFormers is available (SwiGLU)")
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
>   warnings.warn("xFormers is available (Attention)")
> C:\Users\User\documents\github\lhm\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
>   warnings.warn("xFormers is available (Block)")
> ==========skip_decoder:True
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
> CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
>   warnings.warn(error_message)
> load voxel_grid voxel_192.pth
> <All keys matched successfully>
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
>   warnings.warn(
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
>   warnings.warn(msg)
> WARNING:LHM.models.encoders.sapiens_warpper:======== Freezing Sapiens Model ========
> Loading weights from local directory
> * Running on local URL:  http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.
> ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
> handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\User\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
>     self._sock.shutdown(socket.SHUT_RDWR)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> subdir_path and uid:  raw
> C:\Users\User\AppData\Local\Temp\tmpl63d85c0\raw.png ./train_data/motion_video/nezha\smplx_params C:\Users\User\AppData\Local\Temp\tmpl63d85c0 C:\Users\User\AppData\Local\Temp\tmpl63d85c0\output.mp4
> BiRefNet is ready to use.
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
>   x = F.scaled_dot_product_attention(
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
>   return F.conv2d(input, weight, bias, self.stride,
> C:\Users\User\documents\github\lhm\.venv\lib\site-packages\torch\nn\modules\module.py:1541: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
>   return forward_call(*args, **kwargs)
> ```

this error seems to you do not install  triton?

**Comment by Deathdadev** [comment]
No I didnt install triton, and I am aware of that error. I let it run on my system and it turns out that it was actually working, I just didn't know since there was no way for me to track its progress
