### ISSUE TITLE
LHM local variable 'cfg' referenced before assignment

### ISSUE THREAD

**Issue by NGwr** [aigc3d/LHM#75]
LHM
local variable 'cfg' referenced before assignment
报错之后重新启动后台就可以再运行一次，第二次继续这样报错。

(base) PS C:\Users\admin> conda activate lhm_comfy
(lhm_comfy) PS C:\Users\admin> cd E:\待测试\LHM\ComfyUI
(lhm_comfy) PS E:\待测试\LHM\ComfyUI> python main.py
Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.
Total VRAM 24576 MB, total RAM 32581 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers attention
ComfyUI version: 0.3.27
ComfyUI frontend version: 1.14.6
[Prompt Server] web root: C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\comfyui_frontend_package\static

Import times for custom nodes:
   0.0 seconds: E:\待测试\LHM\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   4.8 seconds: E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
[896]
Loading model...
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM/../ComfyUI-LHM\lib_lhm\engine\pose_estimation/../..\engine\pose_estimation/../pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM/../ComfyUI-LHM\lib_lhm\engine\pose_estimation/../..\engine\pose_estimation/../pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM/../ComfyUI-LHM\lib_lhm\engine\pose_estimation/../..\engine\pose_estimation/../pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
using MLP layer as FFN
person center is head
Model loaded
MOTIONPATH: E:\待测试\LHM\ComfyUI\input\1021_00008.mp4
######start to process input#######
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
w head input!
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
apex is not installed
apex is not installed
apex is not installed
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[896]
Loading model...
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
load hmr
load checkpoint from local path: ./models/checkpoints/LHM/pretrained_models/human_model_files\pose_estimate\vitpose-h-wholebody.pth
load detection
load smplx
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
100%|█████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 113.55it/s, Loss: 13.5]
100%|██████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 16.24it/s, Loss: 19.4]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 13.12it/s]
E:\待测试\LHM\ComfyUI\input\1021_00008.mp4 processing completed, duration: 11.76s
E:\待测试\LHM\ComfyUI\input\1021_00008\smplx_params
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\LHM\models\encoders\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\LHM\models\encoders\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\LHM\models\encoders\dinov2\layers\block.py:39: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
using MLP layer as FFN
==========skip_decoder:True
smplx ./models/checkpoints/LHM/pretrained_models/human_model_files
smplx ./models/checkpoints/LHM/pretrained_models/human_model_files
smplx ./models/checkpoints/LHM/pretrained_models/human_model_files
flame ./models/checkpoints/LHM/pretrained_models/human_model_files
flame ./models/checkpoints/LHM/pretrained_models/human_model_files
flame ./models/checkpoints/LHM/pretrained_models/human_model_files
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torch\amp\autocast_mode.py:267: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16, torch.float16 currently.
  warnings.warn(error_message)
load voxel_grid voxel_192.pth
<All keys matched successfully>
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Loading weights from local directory
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torch\nn\modules\module.py:1541: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  return forward_call(*args, **kwargs)
time elapsed: 1.4045743942260742
(21, 1536, 864, 3) 255
Prompt executed in 198.14 seconds
got prompt
MOTIONPATH: E:\待测试\LHM\ComfyUI\input\bandicam 2025-01-07 11-45-55-632.mp4
######start to process input#######
w head input!
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
apex is not installed
apex is not installed
apex is not installed
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
usage: video2motion.py [-h] --video_path VIDEO_PATH [--output_path OUTPUT_PATH] [--model_path MODEL_PATH]
                       [--pad_ratio PAD_RATIO] [--kp_mode KP_MODE] [--visualize]
video2motion.py: error: unrecognized arguments: 2025-01-07 11-45-55-632.mp4
E:\待测试\LHM\ComfyUI\input\bandicam 2025-01-07 11-45-55-632\smplx_params
!!! Exception during processing !!! stack expects a non-empty TensorList
Traceback (most recent call last):
  File "E:\待测试\LHM\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\LHM_Nodes.py", line 407, in execute
    motion_seq = prepare_motion_seqs(
  File "E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM/../ComfyUI-LHM\lib_lhm\LHM\runners\infer\utils.py", line 468, in prepare_motion_seqs
    c2ws = torch.stack(c2ws, dim=0)  # [N, 4, 4]
RuntimeError: stack expects a non-empty TensorList

Prompt executed in 15.15 seconds
got prompt
MOTIONPATH: E:\待测试\LHM\ComfyUI\input\222.mp4
######start to process input#######
w head input!
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
apex is not installed
apex is not installed
apex is not installed
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[896]
Loading model...
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\lib_lhm\engine\pose_estimation\blocks/../dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
load hmr
load checkpoint from local path: ./models/checkpoints/LHM/pretrained_models/human_model_files\pose_estimate\vitpose-h-wholebody.pth
load detection
load smplx
C:\Users\admin\.conda\envs\lhm_comfy\lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
100%|██████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 104.69it/s, Loss: nan]
100%|███████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 16.60it/s, Loss: nan]
100%|██████████████████████████████████████████████████████████████████████████████████| 63/63 [00:00<00:00, 68.49it/s]
E:\待测试\LHM\ComfyUI\input\222.mp4 processing completed, duration: 10.65s
E:\待测试\LHM\ComfyUI\input\222\smplx_params
!!! Exception during processing !!! local variable 'cfg' referenced before assignment
Traceback (most recent call last):
  File "E:\待测试\LHM\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\待测试\LHM\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\待测试\LHM\ComfyUI\custom_nodes\ComfyUI-LHM\LHM_Nodes.py", line 422, in execute
    lhm = _build_model(cfg)
UnboundLocalError: local variable 'cfg' referenced before assignment

Prompt executed in 66.10 seconds

**Comment by lingtengqiu** [comment]
@hitsz-zuoqi

**Comment by hitsz-zuoqi** [comment]
I have fixed this issue,pull the newest code will avoid this

**Comment by NGwr** [comment]
> 我已经修复了这个问题，拉取最新的代码就可以避免这个问题


PS E:\ceshi\LHM\ComfyUI\LHM> git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 2), reused 4 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 415 bytes | 1024 bytes/s, done.
From https://github.com/aigc3d/LHM
   815bab5..fd3d670  feat/comfyui -> origin/feat/comfyui
Updating 815bab5..fd3d670
Fast-forward
 ComfyUI-LHM/LHM_Nodes.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
PS E:\ceshi\LHM\ComfyUI\LHM>
