### ISSUE TITLE
安装pytorch3d正确,运行相关测试也可以通过,但是运行app.py出错

### ISSUE THREAD

**Issue by xlostpanda** [aigc3d/LHM#83]
![Image](https://github.com/user-attachments/assets/96596ff3-b378-4cd8-b568-56776a73aa9e)

相关测试代码:
import torch
print(f'PyTorch version: {torch.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')

if torch.cuda.is_available():
    print(f'CUDA version: {torch.version.cuda}')
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'Compute Capability: {torch.cuda.get_device_capability()}')
    try:
        from pytorch3d.ops import knn_points
        print('--- Attempting pytorch3d.ops.knn_points test ---')
        # Create dummy data on GPU
        points1 = torch.rand(1, 10, 3, device='cuda')
        points2 = torch.rand(1, 20, 3, device='cuda')
        print("Dummy data created on GPU successfully.")
        # Run knn_points
        print("Running knn_points...")
        knn_result = knn_points(points1, points2, K=1)
        print("knn_points executed successfully!")
        print("--- Basic pytorch3d CUDA operation successful ---")
    except ImportError:
        print("ERROR: Failed to import pytorch3d.ops. Is pytorch3d installed correctly?")
    except RuntimeError as e:
        print(f"ERROR: RuntimeError during pytorch3d test: {e}")
        if "no kernel image is available" in str(e):
            print(">>> This confirms the 'no kernel image available' issue persists for knn_points.")
        else:
            print(">>> An unexpected RuntimeError occurred.")
    except Exception as e:
        print(f"ERROR: An unexpected error occurred during pytorch3d test: {e}")
else:
    print('CUDA not available to PyTorch.')

print("--- Test finished ---")

运行app.py 报错:
(LHM) W:\GIT_Workspace\LHM>python .\app.py
Traceback (most recent call last):
  File "W:\GIT_Workspace\LHM\app.py", line 48, in <module>
    from LHM.runners.infer.utils import (
  File "W:\GIT_Workspace\LHM\LHM\runners\__init__.py", line 20, in <module>
    from .infer import *
  File "W:\GIT_Workspace\LHM\LHM\runners\infer\__init__.py", line 16, in <module>
    from .human_lrm import HumanLRMInferrer
  File "W:\GIT_Workspace\LHM\LHM\runners\infer\human_lrm.py", line 37, in <module>
    from LHM.models.modeling_human_lrm import ModelHumanLRM
  File "W:\GIT_Workspace\LHM\LHM\models\__init__.py", line 16, in <module>
    from .modeling_human_lrm import (
  File "W:\GIT_Workspace\LHM\LHM\models\modeling_human_lrm.py", line 22, in <module>
    from LHM.models.rendering.gs_renderer import GS3DRenderer, PointEmbed
  File "W:\GIT_Workspace\LHM\LHM\models\rendering\gs_renderer.py", line 13, in <module>
    from diff_gaussian_rasterization import (
  File "D:\Anaconda3\envs\LHM\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: 找不到指定的模块。

pip list:
(LHM) W:\GIT_Workspace\LHM>pip list
Package                     Version
--------------------------- ------------------
absl-py                     2.2.2
accelerate                  1.6.0
addict                      2.4.0
aiofiles                    23.2.1
aiohappyeyeballs            2.6.1
aiohttp                     3.11.16
aiosignal                   1.3.2
annotated-types             0.7.0
antlr4-python3-runtime      4.9.3
anyio                       4.6.2
argon2-cffi                 21.3.0
argon2-cffi-bindings        21.2.0
asttokens                   3.0.0
async-lru                   2.0.4
async-timeout               5.0.1
attrs                       24.3.0
autocommand                 2.2.2
babel                       2.16.0
backports.tarfile           1.2.0
basicsr                     1.4.2
bcrypt                      4.3.0
beautifulsoup4              4.12.3
black                       25.1.0
bleach                      6.2.0
blinker                     1.9.0
boto3                       1.37.30
botocore                    1.37.30
Brotli                      1.0.9
certifi                     2025.1.31
cffi                        1.17.1
charset-normalizer          3.3.2
chumpy                      0.71
click                       8.1.8
colorama                    0.4.6
coloredlogs                 15.0.1
comm                        0.2.1
ConfigArgParse              1.7
cryptography                44.0.2
cycler                      0.12.1
dash                        3.0.2
dataclasses-json            0.6.7
debugpy                     1.8.11
decorator                   5.1.1
decord                      0.6.0
defusedxml                  0.7.1
Deprecated                  1.2.18
diff_gaussian_rasterization 0.0.0
diffusers                   0.32.0
dna                         0.0.1
einops                      0.8.1
exceptiongroup              1.2.0
executing                   0.8.3
facexlib                    0.3.0
fastapi                     0.115.12
fastjsonschema              2.20.0
ffmpy                       0.5.0
filelock                    3.13.1
filterpy                    1.4.5
flake8                      7.2.0
flake8-bugbear              24.12.12
flake8-comprehensions       3.16.0
Flask                       3.0.3
flatbuffers                 25.2.10
fonttools                   4.57.0
freetype-py                 2.5.1
frozenlist                  1.5.0
fsspec                      2024.6.1
future                      1.0.0
fvcore                      0.1.5.post20221221
gfpgan                      1.3.8
GPUtil                      1.4.0
gradio                      5.24.0
gradio_client               1.8.0
groovy                      0.1.2
grpcio                      1.71.0
gsplat                      1.4.0
h11                         0.14.0
httpcore                    1.0.2
httpx                       0.27.0
huggingface-hub             0.30.2
humanfriendly               10.0
hydra-core                  1.3.2
idna                        3.10
imageio                     2.34.1
imageio-ffmpeg              0.6.0
importlib_metadata          8.6.1
importlib_resources         6.5.2
inflect                     7.3.1
intel-openmp                2021.4.0
iopath                      0.1.10
ipykernel                   6.29.5
ipython                     8.30.0
ipywidgets                  8.1.5
itsdangerous                2.2.0
jaraco.context              5.3.0
jaraco.functools            4.0.1
jaraco.text                 3.12.1
jaxtyping                   0.2.38
jedi                        0.19.2
Jinja2                      3.1.4
jmespath                    1.0.1
json5                       0.9.25
jsonschema                  4.23.0
jsonschema-specifications   2023.7.1
jupyter                     1.1.1
jupyter_client              8.6.3
jupyter-console             6.6.3
jupyter_core                5.7.2
jupyter-events              0.12.0
jupyter-lsp                 2.2.0
jupyter_server              2.15.0
jupyter_server_terminals    0.4.4
jupyterlab                  4.3.4
jupyterlab_pygments         0.3.0
jupyterlab_server           2.27.3
jupyterlab_widgets          3.0.13
kiui                        0.2.14
kiwisolver                  1.4.8
kornia                      0.7.2
kornia_rs                   0.1.8
lazy_loader                 0.4
libcst                      1.7.0
lightning-utilities         0.14.3
llvmlite                    0.43.0
lmdb                        1.6.2
loguru                      0.7.3
lpips                       0.1.4
Markdown                    3.7
markdown-it-py              3.0.0
MarkupSafe                  2.1.5
marshmallow                 3.26.1
matplotlib                  3.5.3
matplotlib-inline           0.1.6
mccabe                      0.7.0
mdurl                       0.1.2
megfile                     4.1.0.post2
mistune                     3.1.2
mkl                         2021.4.0
modelscope                  1.24.1
more-itertools              10.3.0
moreorless                  0.4.0
mpmath                      1.3.0
multidict                   6.2.0
mypy-extensions             1.0.0
narwhals                    1.34.0
nbclient                    0.10.2
nbconvert                   7.16.6
nbformat                    5.10.4
nest-asyncio                1.6.0
networkx                    3.3
ninja                       1.11.1.4
notebook                    7.3.2
notebook_shim               0.2.4
numba                       0.60.0
numpy                       1.24.3
nvdiffrast                  0.3.1
objprint                    0.3.0
omegaconf                   2.3.0
onnxruntime                 1.14.0
open3d                      0.19.0
opencv-python               4.11.0.86
opencv-python-headless      4.11.0.86
orjson                      3.10.16
overrides                   7.4.0
packaging                   24.2
pandas                      2.2.3
pandocfilters               1.5.0
paramiko                    3.5.1
parso                       0.8.4
pathspec                    0.12.1
pillow                      10.4.0
pip                         25.0
platformdirs                3.10.0
plotly                      6.0.1
plyfile                     1.1
pooch                       1.8.2
portalocker                 3.1.1
prometheus_client           0.21.0
prompt-toolkit              3.0.43
propcache                   0.3.1
protobuf                    6.30.2
psutil                      5.9.0
pure-eval                   0.2.2
pycodestyle                 2.13.0
pycparser                   2.21
pydantic                    2.11.3
pydantic_core               2.33.1
pydub                       0.25.1
pyflakes                    3.3.2
pyglet                      2.1.3
pygltflib                   1.16.2
Pygments                    2.15.1
PyMatting                   1.1.13
PyNaCl                      1.5.0
PyOpenGL                    3.1.0
pyparsing                   3.2.3
PyQt6                       6.7.1
PyQt6_sip                   13.9.1
pyreadline3                 3.5.4
pyrender                    0.1.45
PySocks                     1.7.1
python-dateutil             2.9.0.post0
python-json-logger          3.2.1
python-multipart            0.0.20
pytorch-lightning           2.5.1
pytorch3d                   0.7.8
pytz                        2025.2
pywin32                     308
pywinpty                    2.0.15
PyYAML                      6.0.1
pyzmq                       26.2.0
qtconsole                   5.6.1
QtPy                        2.4.1
referencing                 0.30.2
regex                       2024.11.6
rembg                       2.0.63
requests                    2.32.3
retrying                    1.3.4
rfc3339-validator           0.1.4
rfc3986-validator           0.1.1
rich                        14.0.0
roma                        1.5.2.1
rpds-py                     0.22.3
ruff                        0.11.4
s3transfer                  0.11.4
safehttpx                   0.1.6
safetensors                 0.5.3
SAM-2                       1.0
scikit-image                0.24.0
scipy                       1.13.1
semantic-version            2.10.0
Send2Trash                  1.8.2
setuptools                  74.0.0
shellingham                 1.5.4
simple_knn                  1.0.0
sip                         6.10.0
six                         1.16.0
smplx                       0.1.28
sniffio                     1.3.0
soupsieve                   2.5
spaces                      0.34.2
stack-data                  0.2.0
starlette                   0.46.1
stdlibs                     2025.4.4
sympy                       1.13.1
tabulate                    0.9.0
taming-transformers-rom1504 0.0.6
tb-nightly                  2.20.0a20250408
tbb                         2021.11.0
tensorboard-data-server     0.7.2
termcolor                   3.0.1
terminado                   0.17.1
tifffile                    2025.3.30
timm                        1.0.15
tinycss2                    1.4.0
tokenizers                  0.19.1
toml                        0.10.2
tomli                       2.0.1
tomlkit                     0.12.0
torch                       2.3.0
torchaudio                  2.3.0
torchmetrics                1.7.1
torchsde                    0.2.6
torchvision                 0.18.0
tornado                     6.4.2
tqdm                        4.66.4
trailrunner                 1.4.0
traitlets                   5.14.3
trampoline                  0.1.2
transformers                4.41.2
trimesh                     4.4.9
typeguard                   2.13.3
typer                       0.15.2
typing_extensions           4.12.2
typing-inspect              0.9.0
typing-inspection           0.4.0
tzdata                      2025.2
urllib3                     2.3.0
usort                       1.0.8.post1
uvicorn                     0.34.0
varname                     0.14.0
wadler_lindig               0.1.4
wcwidth                     0.2.13
webencodings                0.5.1
websocket-client            1.8.0
websockets                  12.0
Werkzeug                    3.0.6
wheel                       0.45.1
widgetsnbextension          4.0.13
win-inet-pton               1.1.0
win32_setctime              1.2.0
wrapt                       1.17.2
xatlas                      0.0.9
yacs                        0.1.8
yapf                        0.43.0
yarl                        1.19.0
zipp                        3.21.0

**Comment by hitsz-zuoqi** [comment]
你这个是diff-gaussian没编译好

**Comment by xlostpanda** [comment]
![Image](https://github.com/user-attachments/assets/463933af-8679-43c0-ac8a-4d2fb72994fb)

已经解决,谢谢各位,确实是diff-gaussian的问题,重新编译就好了
