### ISSUE TITLE
为什么用您提供的姿态提取代码，从视频中自己提取姿态数据作输入进行推理的时候会报错，用train_data里您提取好的姿态数据跑推理就没问题？

### ISSUE THREAD

**Issue by robinhood256100** [aigc3d/LHM#87]
大佬你好，我用train_data里您提取好的姿态数据跑推理没问题，但是在用您提供的姿态提取代码，从视频中自己提取姿态数据作输入进行推理的时候就会报下面这个错误，即使是用您提供的demo.mp4（闪电五连鞭）也不行，这是为什么

/home/user2/anaconda3/envs/LHM/lib/python3.10/site-packages/torch/nn/modules/module.py:1541: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return forward_call(*args, **kwargs)
  0%|                                                                                                                                | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/user2/anaconda3/envs/LHM/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user2/anaconda3/envs/LHM/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/fspace/app/LHM/LHM/launch.py", line 37, in <module>
    main()
  File "/mnt/fspace/app/LHM/LHM/launch.py", line 33, in main
    runner.run()
  File "/mnt/fspace/app/LHM/LHM/runners/infer/base_inferrer.py", line 62, in run
    self.infer()
  File "/mnt/fspace/app/LHM/LHM/runners/infer/human_lrm.py", line 880, in infer
    self.infer_single(
  File "/mnt/fspace/app/LHM/LHM/runners/infer/human_lrm.py", line 695, in infer_single
    motion_seq = prepare_motion_seqs(
  File "/mnt/fspace/app/LHM/LHM/runners/infer/utils.py", line 489, in prepare_motion_seqs
    c2ws = torch.stack(c2ws, dim=0)  # [N, 4, 4]
RuntimeError: stack expects a non-empty TensorList

**Comment by lingtengqiu** [comment]
你的文件结构可以给我看看嘛，提取出来的文件结构？ 输入给  inference code 的地址是带smplx_params 的；

**Comment by robinhood256100** [comment]
> 你的文件结构可以给我看看嘛，提取出来的文件结构？ 输入给 inference code 的地址是带smplx_params 的；

感谢大佬的回复，我注意到了这点，提取出来的姿态数据放在./train_data/custom_motion​/demo/smplx_params这个路径下，推理用的下面这条命令
bash ./inference.sh LHM-1B-HF ./train_data/example_imgs/wmx.jpg ./train_data/custom_motion/demo/smplx_params，报了我上面说的那个错误
（File "/mnt/fspace/app/LHM/LHM/runners/infer/human_lrm.py", line 695, in infer_single
motion_seq = prepare_motion_seqs(
File "/mnt/fspace/app/LHM/LHM/runners/infer/utils.py", line 489, in prepare_motion_seqs
c2ws = torch.stack(c2ws, dim=0) # [N, 4, 4]
RuntimeError: stack expects a non-empty TensorList）。

我也尝试了使用您提取好的姿态数据（./train_data/motion_video/girl/smplx_params），用如下命令进行推理：bash ./inference.sh LHM-1B-HF ./train_data/example_imgs/wmx.jpg ./train_data/motion_video/girl/smplx_params，这个就是正常的。

这么看应该就是我提取的姿态数据有问题。
但是我也打开json文件检查了一下，文件中保存的字段内容和您提供的现成的一致，我实在搞不懂哪里出问题了，大佬救命~~

我提取的00001.json中的内容：{"betas": [0.24681976437568665, 0.0806291326880455, 0.4646121561527252, -0.010740537196397781, -0.11239367723464966, -0.087550088763237, -0.0005727238021790981, -0.06748034805059433, -0.16254055500030518, -0.07832414656877518], "root_pose": [3.3394229412078857, -0.008936011232435703, -0.061192601919174194], "body_pose": [[-0.04349217563867569, -0.000991285778582096, 0.08409235626459122], [-0.0332275815308094, -0.03920552134513855, -0.055447861552238464], [0.20462577044963837, 0.009727178141474724, 0.007456543855369091], [0.18702450394630432, -0.08878275752067566, 0.0004863083304371685], [0.21517598628997803, 0.013673288747668266, 0.0017233643447980285], [-0.009198992513120174, -0.010620330460369587, -0.00038209473132155836], [-0.1232696995139122, 0.10836788266897202, -0.04866315796971321], [-0.18950214982032776, -0.18060338497161865, -0.00035217986442148685], [0.008678138256072998, 0.004208827391266823, -0.005697892978787422], [-0.005402370821684599, -0.012825426645576954, 0.005297631956636906], [-0.01055119652301073, 0.00789374578744173, 0.007246037479490042], [0.1063394695520401, -0.01539792399853468, -0.022807439789175987], [0.05182109773159027, -0.15040472149848938, -0.2436375916004181], [0.038510892540216446, 0.15165725350379944, 0.18740151822566986], [-0.0728876069188118, -0.04234373942017555, -0.045820388942956924], [0.2900885343551636, -0.24467523396015167, -0.9450213313102722], [0.31311652064323425, 0.25013166666030884, 0.9924473762512207], [0.3571520745754242, -0.6038318872451782, -0.052617594599723816], [0.38094985485076904, 0.7320119738578796, 0.009119080379605293], [-0.13106301426887512, -0.5063818693161011, -0.026278337463736534], [-0.16291455924510956, 0.4524455964565277, -0.09114564210176468]], "jaw_pose": [0.034007295966148376, -0.0007511227740906179, 0.020158378407359123], "leye_pose": [0.0, 0.0, 0.0], "reye_pose": [0.0, 0.0, 0.0], "lhand_pose": [[0.07223497331142426, 0.40623530745506287, -0.620036780834198], [0.1914357990026474, -0.02628261223435402, -0.5321051478385925], [-0.0718071386218071, -0.1350599229335785, -0.06539388000965118], [-0.177094504237175, 0.21083004772663116, -0.9200581312179565], [-0.06852376461029053, 0.05741116777062416, -0.2672811448574066], [-0.002820286899805069, -0.132447749376297, -0.2824593186378479], [-0.5583925247192383, -0.584409236907959, -0.6579606533050537], [-0.06152917817234993, -0.04927140846848488, -0.31423646211624146], [-0.44494694471359253, -0.033181097358465195, 0.030401580035686493], [-0.15317168831825256, -0.182583287358284, -0.9241496920585632], [-0.29815301299095154, -0.07772000133991241, -0.20411255955696106], [-0.20487599074840546, -0.12626685202121735, -0.2908948063850403], [0.8211217522621155, 0.5057997107505798, 0.009502061642706394], [-0.5733727812767029, 0.018539749085903168, -0.12009696662425995], [0.6092526912689209, 0.18873849511146545, -0.14111651480197906]], "rhand_pose": [[0.05384847894310951, -0.31152498722076416, 0.30231279134750366], [0.1726572960615158, 0.011849536560475826, 0.2682019770145416], [-0.10168219357728958, 0.123716339468956, -0.018038367852568626], [-0.11829748004674911, -0.13299871981143951, 0.444182813167572], [-0.07604127377271652, -0.047325458377599716, 0.05845525488257408], [-0.013651849702000618, 0.1234000101685524, 0.13750769197940826], [-0.3568873703479767, 0.5075244903564453, 0.30038392543792725], [0.1174725741147995, -0.037821341305971146, 0.14797045290470123], [-0.3597998023033142, -0.0051455190405249596, -0.16110536456108093], [-0.020531291142106056, 0.09680327028036118, 0.4960254430770874], [-0.22612769901752472, 0.05466704070568085, -0.088599294424057], [-0.1649925261735916, 0.08749935030937195, 0.15894217789173126], [0.7827573418617249, -0.43008679151535034, -0.05470037832856178], [-0.5961096286773682, -0.031057873740792274, 0.06855343282222748], [0.5507165193557739, -0.10033059120178223, 0.12262070178985596]], "trans": [0.0035568149760365486, 0.25162428617477417, 2.049699068069458], "focal": [1330.2149658203125, 1330.2149658203125], "princpt": [432.0, 768.0], "img_size_wh": [864, 1536], "pad_ratio": 0.2}

**Comment by lingtengqiu** [comment]
你是comfyui 还是源码？

**Comment by lingtengqiu** [comment]
我看是源码， 你的运行脚本可以发我们看看吗？

**Comment by robinhood256100** [comment]
对，我是用源码跑的，
提取关键点的命令：python ./engine/pose_estimation/video2motion.py --video_path ./train_data/demo.mp4 --output_path ./train_data/custom_motion​ 

推理的命令：bash ./inference.sh LHM-1B-HF ./train_data/example_imgs/wmx.jpg ./train_data/custom_motion/demo/smplx_params

**提取关键点的脚本（video2motion.py）有500多行，我没动过，放在附件里了；下面是推理的脚本inference.sh的内容，我也没动**

#!/bin/bash
# given pose sequence, generating animation video .

MODEL_NAME=LHM-1B
IMAGE_INPUT="./train_data/example_imgs/"
MOTION_SEQS_DIR="./train_data/motion_video/mimo6/smplx_params/"

MODEL_NAME=${1:-$MODEL_NAME}
IMAGE_INPUT=${2:-$IMAGE_INPUT}
MOTION_SEQS_DIR=${3:-$MOTION_SEQS_DIR}

echo "IMAGE_INPUT: $IMAGE_INPUT"
echo "MODEL_NAME: $MODEL_NAME"
echo "MOTION_SEQS_DIR: $MOTION_SEQS_DIR"

echo "INFERENCE VIDEO"

MOTION_IMG_DIR=None
VIS_MOTION=true
MOTION_IMG_NEED_MASK=true
RENDER_FPS=30
MOTION_VIDEO_READ_FPS=30
EXPORT_VIDEO=True

python -m LHM.launch infer.human_lrm model_name=$MODEL_NAME \
        image_input=$IMAGE_INPUT \
        export_video=$EXPORT_VIDEO \
        motion_seqs_dir=$MOTION_SEQS_DIR motion_img_dir=$MOTION_IMG_DIR  \
        vis_motion=$VIS_MOTION motion_img_need_mask=$MOTION_IMG_NEED_MASK \
        render_fps=$RENDER_FPS motion_video_read_fps=$MOTION_VIDEO_READ_FPS

**Comment by robinhood256100** [comment]
姿态提取脚本：
# -*- coding: utf-8 -*-
# @Organization  : Alibaba XR-Lab
# @Author        : Peihao Li
# @Email         : liphao99@gmail.com
# @Time          : 2025-03-19 12:47:58
# @Function      : video motion process pipeline
import copy
import json
import os
import sys
from math import sqrt

current_dir_path = os.path.dirname(__file__)
sys.path.append(current_dir_path + "/../pose_estimation")
import argparse
import copy
import gc
import json
import os
import random
import sys
import time

import cv2
import numpy as np
import torch
import torch.nn.functional as F
from blocks import SMPL_Layer
from blocks.detector import DetectionModel
from model import forward_model, load_model
from pose_utils.constants import KEYPOINT_THR
from pose_utils.image import img_center_padding, normalize_rgb_tensor
from pose_utils.inference_utils import get_camera_parameters
from pose_utils.postprocess import OneEuroFilter, smplx_gs_smooth
from pose_utils.render import render_video
from pose_utils.tracker import bbox_xyxy_to_cxcywh, track_by_area
from smplify import TemporalSMPLify

torch.cuda.empty_cache()

np.random.seed(seed=0)
random.seed(0)


def load_video(video_path, pad_ratio, max_resolution):
    cap = cv2.VideoCapture(video_path)
    assert cap.isOpened(), f"fail to load video file {video_path}"
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    downsample_factor = -1
    if (height * width) > max_resolution:
        downsample_factor = sqrt(max_resolution / (height * width))
        height = int(height * downsample_factor)
        width = int(width * downsample_factor)

    frames = []
    offset_w, offset_h = 0, 0
    while cap.isOpened():
        flag, frame = cap.read()
        if not flag:
            break

        # since the tracker and detector receive BGR images as inputs
        # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        if downsample_factor > 0:
            frame = cv2.resize(
                frame,
                (width, height),
                interpolation=cv2.INTER_AREA,
            )
        if pad_ratio > 0:
            frame, offset_w, offset_h = img_center_padding(frame, pad_ratio)
        frames.append(frame)
    height, width, _ = frames[0].shape
    return frames, height, width, fps, offset_w, offset_h


def images_crop(images, bboxes, target_size, device=torch.device("cuda")):
    # bboxes: cx, cy, w, h
    crop_img_list = []
    crop_annotations = []
    i = 0
    raw_img_size = max(images[0].shape[:2])
    for img, bbox in zip(images, bboxes):

        left = max(0, int(bbox[0] - bbox[2] // 2))
        right = min(img.shape[1] - 1, int(bbox[0] + bbox[2] // 2))
        top = max(0, int(bbox[1] - bbox[3] // 2))
        bottom = min(img.shape[0] - 1, int(bbox[1] + bbox[3] // 2))
        crop_img = img[top:bottom, left:right]
        crop_img = torch.Tensor(crop_img).to(device).unsqueeze(0).permute(0, 3, 1, 2)

        _, _, h, w = crop_img.shape
        scale_factor = min(target_size / w, target_size / h)
        crop_img = F.interpolate(crop_img, scale_factor=scale_factor, mode="bilinear")

        _, _, h, w = crop_img.shape
        pad_left = (target_size - w) // 2
        pad_top = (target_size - h) // 2
        pad_right = target_size - w - pad_left
        pad_bottom = target_size - h - pad_top
        crop_img = F.pad(
            crop_img,
            (pad_left, pad_right, pad_top, pad_bottom),
            mode="constant",
            value=0,
        )

        resize_img = normalize_rgb_tensor(crop_img)

        crop_img_list.append(resize_img)
        crop_annotations.append(
            (
                left,
                top,
                pad_left,
                pad_top,
                scale_factor,
                target_size / scale_factor,
                raw_img_size,
            )
        )

    return crop_img_list, crop_annotations


def generate_pseudo_idx(keypoints, patch_size, n_patch, crop_annotation):

    device = keypoints.device
    anchors = torch.stack([keypoints[3], keypoints[4], keypoints[5], keypoints[6]])

    mask = anchors[..., -1] >= KEYPOINT_THR
    if mask.sum() < 2:

        return None, None
    anchors = anchors[mask, :2]  # N, 2

    radius = torch.norm(anchors.max(dim=0)[0] - anchors.min(dim=0)[0]) / 2

    head_pseudo_loc = anchors.mean(0)
    if crop_annotation is not None:
        left, top, pad_left, pad_top, scale_factor, crop_size, raw_size = (
            crop_annotation
        )
        head_pseudo_loc = (
            head_pseudo_loc - torch.tensor([left, top], device=device)
        ) * scale_factor + torch.tensor([pad_left, pad_top], device=device)
        radius = radius * scale_factor
    coarse_loc = (head_pseudo_loc // patch_size).int()  # (nhv,2)
    pseudo_idx = torch.clamp(coarse_loc, 0, n_patch - 1)  # (nhv,2)
    pseudo_idx = (
        torch.zeros((1,), dtype=torch.int32, device=device),
        pseudo_idx[1:2],
        pseudo_idx[0:1],
        torch.zeros((1,), dtype=torch.int32, device=device),
    )
    max_dist = (radius // patch_size).int()
    if max_dist < 2:
        max_dist = None
    return pseudo_idx, max_dist


def project2origin_img(target_human, crop_annotation):
    if target_human is None:
        return target_human
    left, top, pad_left, pad_top, scale_factor, crop_size, raw_size = crop_annotation
    device = target_human["loc"].device

    target_human["loc"] = (
        target_human["loc"] - torch.tensor([pad_left, pad_top], device=device)
    ) / scale_factor + torch.tensor([left, top], device=device)

    target_human["dist"] = target_human["dist"] / (crop_size / raw_size)
    return target_human


def empty_frame_pad(pose_results):
    if len(pose_results) == 1:
        return pose_results
    all_is_None = True
    for i in range(1, len(pose_results)):
        if pose_results[i] is None and pose_results[i - 1] is not None:
            pose_results[i] = copy.deepcopy(pose_results[i - 1])
        if pose_results[i] is not None:
            all_is_None = False
    if all_is_None:
        return []
    for i in range(len(pose_results) - 2, -1, -1):
        if pose_results[i] is None and pose_results[i + 1] is not None:
            pose_results[i] = copy.deepcopy(pose_results[i + 1])
    return pose_results


def parse_chunks(
    frame_ids,
    pose_results,
    k2d,
    bboxes,
    min_len=10,
):
    """If a track disappear in the middle,
    we separate it to different segments
    """
    data_chunks = []
    if isinstance(frame_ids, list):
        frame_ids = np.array(frame_ids)
    step = frame_ids[1:] - frame_ids[:-1]
    step = np.concatenate([[0], step])
    breaks = np.where(step != 1)[0]
    start = 0
    for bk in breaks[1:]:
        f_chunk = frame_ids[start:bk]

        if len(f_chunk) >= min_len:
            data_chunk = {
                "frame_id": f_chunk,
                "keypoints_2d": k2d[start:bk],
                "bbox": bboxes[start:bk],
                "rotvec": [],
                "beta": [],
                "loc": [],
                "dist": [],
            }
            padded_pose_results = empty_frame_pad(pose_results[start:bk])

            for pose_result in padded_pose_results:
                data_chunk["rotvec"].append(pose_result["rotvec"])
                data_chunk["beta"].append(pose_result["shape"])
                data_chunk["loc"].append(pose_result["loc"])
                data_chunk["dist"].append(pose_result["dist"])
            if len(padded_pose_results) > 0:
                data_chunks.append(data_chunk)
        start = bk

    start = breaks[-1]  # last chunk
    bk = len(frame_ids)
    f_chunk = frame_ids[start:bk]

    if len(f_chunk) >= min_len:
        data_chunk = {
            "frame_id": f_chunk,
            "keypoints_2d": k2d[start:bk].clone().detach(),
            "bbox": bboxes[start:bk].clone().detach(),
            "rotvec": [],
            "beta": [],
            "loc": [],
            "dist": [],
        }
        padded_pose_results = empty_frame_pad(pose_results[start:bk])
        for pose_result in padded_pose_results:
            data_chunk["rotvec"].append(pose_result["rotvec"])
            data_chunk["beta"].append(pose_result["shape"])
            data_chunk["loc"].append(pose_result["loc"])
            data_chunk["dist"].append(pose_result["dist"])

        if len(padded_pose_results) > 0:

            data_chunks.append(data_chunk)

    for data_chunk in data_chunks:
        for key in ["rotvec", "beta", "loc", "dist"]:
            try:
                data_chunk[key] = torch.stack(data_chunk[key])
            except:
                print(key)

    return data_chunks


def load_models(model_path, device):
    ckpt_path = os.path.join(model_path, "pose_estimate", "multiHMR_896_L.pt")
    pose_model = load_model(ckpt_path, model_path, device=device)
    print("load hmr")
    pose_model_ckpt = os.path.join(
        model_path, "pose_estimate", "vitpose-h-wholebody.pth"
    )
    keypoint_detector = DetectionModel(pose_model_ckpt, device)
    print("load detection")
    smplx_model = SMPL_Layer(
        model_path,
        type="smplx",
        gender="neutral",
        num_betas=10,
        kid=False,
        person_center="head",
    ).to(device)
    print("load smplx")
    return pose_model, keypoint_detector, smplx_model


class Video2MotionPipeline:
    def __init__(
        self,
        model_path,
        fitting_steps,
        device,
        kp_mode="vitpose",
        visualize=True,
        pad_ratio=0.2,
        fov=60,
    ):
        self.MAX_RESOLUTION = 1289 * 720
        self.device = device
        self.visualize = visualize
        self.kp_mode = kp_mode
        self.pad_ratio = pad_ratio
        self.fov = fov
        self.fps = None
        self.pose_model, self.keypoint_detector, self.smplx_model = load_models(
            model_path, self.device
        )
        self.smplx_model.to(self.device)
        self.smplify = TemporalSMPLify(
            smpl=self.smplx_model, device=self.device, num_steps=fitting_steps
        )

    def track(self, all_frames):
        self.keypoint_detector.initialize_tracking()
        for frame in all_frames:
            self.keypoint_detector.track(frame, self.fps, len(all_frames))
        tracking_results = self.keypoint_detector.process(self.fps)
        # note: only surpport pose estimation for one character
        main_character = None
        max_frame_length = -1
        for _id in tracking_results.keys():
            if len(tracking_results[_id]["frame_id"]) > max_frame_length:
                max_frame_length = len(tracking_results[_id]["frame_id"])
                main_character = _id

        bboxes = tracking_results[main_character]["bbox"]
        frame_ids = tracking_results[main_character]["frame_id"]
        frames = [all_frames[i] for i in frame_ids]
        assert not (bboxes[0][0] == 0 and bboxes[0][2] == 0)

        return bboxes, frame_ids, frames

    def detect_keypoint2d(self, bboxes, frames):
        if self.kp_mode == "vitpose":
            keypoints, bboxes = self.keypoint_detector.batch_detection(bboxes, frames)
        else:
            raise NotImplementedError
        return bboxes, keypoints

    def estimate_pose(self, frame_ids, frames, keypoints, bboxes, raw_K, video_length):
        target_img_size = self.pose_model.img_size
        patch_size = self.pose_model.patch_size

        K = get_camera_parameters(
            target_img_size, fov=self.fov, p_x=None, p_y=None, device=self.device
        )

        keypoints = torch.tensor(keypoints, device=self.device)
        bboxes = torch.tensor(bboxes, device=self.device)
        bboxes = bbox_xyxy_to_cxcywh(bboxes, scale=1.5)

        crop_images, crop_annotations = images_crop(
            frames, bboxes, target_size=target_img_size, device=self.device
        )

        all_frame_results = []
        # model inference
        for i, image in enumerate(crop_images):

            # Calculate the possible search area for the primary joint (head) based on 2D keypoints
            # pseudo_idx: The index of the search area center after patching
            # max_dist: The maximum radius of the search area
            pseudo_idx, max_dist = generate_pseudo_idx(
                keypoints[i],
                patch_size,
                int(target_img_size / patch_size),
                crop_annotations[i],
            )
            humans = forward_model(
                self.pose_model, image, K, pseudo_idx=pseudo_idx, max_dist=max_dist
            )
            target_human = track_by_area(humans, target_img_size)
            target_human = project2origin_img(target_human, crop_annotations[i])

            all_frame_results.append(target_human)

        # parse chunk & missed frame padding
        data_chunks = parse_chunks(
            frame_ids,
            all_frame_results,
            keypoints,
            bboxes,
            min_len=int(self.fps / 10),
        )

        trans_cam_fill = np.zeros((video_length, 3))
        smpl_poses_cam_fill = np.zeros((video_length, 55, 3))
        smpl_shapes_fill = np.zeros((video_length, 10))
        all_verts = [None] * video_length
        for data_chunk in data_chunks:
            # one_euro filter on 2d keypoints

            one_euro = OneEuroFilter(
                min_cutoff=1.2, beta=0.3, sampling_rate=self.fps, device=self.device
            )
            for i in range(len(data_chunk["keypoints_2d"])):
                data_chunk["keypoints_2d"][i, :, :2] = one_euro.filter(
                    data_chunk["keypoints_2d"][i, :, :2]
                )

            poses, betas, transl = self.smplify.fit(
                data_chunk["rotvec"],
                data_chunk["beta"],
                data_chunk["dist"],
                data_chunk["loc"],
                raw_K,
                data_chunk["keypoints_2d"],
                data_chunk["bbox"],
            )

            # gaussian filter
            with torch.no_grad():

                poses, betas, transl = smplx_gs_smooth(
                    poses, betas, transl, fps=self.fps
                )

                out = self.smplx_model(
                    poses,
                    betas,
                    None,
                    None,
                    transl=transl,
                    K=raw_K,
                    expression=None,
                    rot6d=False,
                )

                transl = out["transl_pelvis"].squeeze(1)
                poses_ = self.smplx_model.convert_standard_pose(poses)
                smpl_poses_cam_fill[data_chunk["frame_id"]] = poses_.cpu().numpy()
                smpl_shapes_fill[data_chunk["frame_id"]] = betas.cpu().numpy()
                trans_cam_fill[data_chunk["frame_id"]] = transl.cpu().numpy()

            for i, frame_id in enumerate(data_chunk["frame_id"]):
                try:
                    if all_verts[frame_id] is None:
                        all_verts[frame_id] = []
                    all_verts[frame_id].append(out["v3d"][i])
                except:
                    break

        return smpl_poses_cam_fill, smpl_shapes_fill, trans_cam_fill, all_verts

    def save_video(
        self, all_frames, frame_ids, bboxes, keypoints, verts, K, out_folder
    ):
        all_frames = [cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) for frame in all_frames]
        save_name = os.path.join(out_folder, "pose_visualized.mp4")

        # 2d keypoints visualization
        for i, frame_id in enumerate(frame_ids):
            keypoint_results = [{"bbox": bboxes[i], "keypoints": keypoints[i]}]

            all_frames[frame_id] = self.keypoint_detector.visualize(
                all_frames[frame_id], keypoint_results
            )

        render_video(
            verts,
            self.pose_model.smpl_layer["neutral_10"].bm_x.faces,
            K,
            all_frames,
            self.fps,
            save_name,
            self.device,
            True,
        )

    def save_results(self, out_path, frame_ids, poses, betas, transl, K, img_wh):
        K = K[0].cpu().numpy()
        for i in frame_ids:

            smplx_param = {}
            smplx_param["betas"] = betas[i].tolist()
            smplx_param["root_pose"] = poses[i, 0].tolist()
            smplx_param["body_pose"] = poses[i, 1:22].tolist()
            smplx_param["jaw_pose"] = poses[i, 22].tolist()
            smplx_param["leye_pose"] = [0.0, 0.0, 0.0]
            smplx_param["reye_pose"] = [0.0, 0.0, 0.0]
            smplx_param["lhand_pose"] = poses[i, 25:40].tolist()
            smplx_param["rhand_pose"] = poses[i, 40:55].tolist()

            smplx_param["trans"] = transl[i].tolist()
            smplx_param["focal"] = [float(K[0, 0]), float(K[1, 1])]
            smplx_param["princpt"] = [float(K[0, 2]), float(K[1, 2])]
            smplx_param["img_size_wh"] = [img_wh[0], img_wh[1]]
            smplx_param["pad_ratio"] = self.pad_ratio
            with open(os.path.join(out_path, f"{(i+1):05}.json"), "w") as fp:
                json.dump(smplx_param, fp)

    def __call__(self, video_path, output_path, is_file_only=False):
        start = time.time()
        all_frames, raw_H, raw_W, fps, offset_w, offset_h = load_video(
            video_path, pad_ratio=self.pad_ratio, max_resolution=self.MAX_RESOLUTION
        )
        self.fps = fps
        video_length = len(all_frames)

        raw_K = get_camera_parameters(
            max(raw_H, raw_W), fov=self.fov, p_x=None, p_y=None, device=self.device
        )
        raw_K[..., 0, -1] = raw_W / 2
        raw_K[..., 1, -1] = raw_H / 2

        bboxes, frame_ids, frames = self.track(all_frames)
        bboxes, keypoints = self.detect_keypoint2d(bboxes, frames)
        gc.collect()
        torch.cuda.empty_cache()

        poses, betas, transl, verts = self.estimate_pose(
            frame_ids, frames, keypoints, bboxes, raw_K, video_length
        )

        if is_file_only:
            output_folder = output_path
        else:
            output_folder = os.path.join(
                output_path, video_path.split("/")[-1].split(".")[0]
            )
        os.makedirs(output_folder, exist_ok=True)

        if self.visualize:
            self.save_video(
                all_frames, frame_ids, bboxes, keypoints, verts, raw_K, output_folder
            )

        smplx_output_folder = os.path.join(output_folder, "smplx_params")
        os.makedirs(smplx_output_folder, exist_ok=True)
        self.save_results(
            smplx_output_folder, frame_ids, poses, betas, transl, raw_K, (raw_W, raw_H)
        )
        duration = time.time() - start
        print(f"{video_path} processing completed, duration: {duration:.2f}s")

        return smplx_output_folder


def get_parse():
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--video_path", type=str, required=True)
    parser.add_argument("--output_path", type=str, default="./train_data/custom_motion")
    parser.add_argument(
        "--model_path",
        type=str,
        default="./pretrained_models/human_model_files",
        help="model_path",
    )
    parser.add_argument(
        "--pad_ratio",
        type=float,
        default=0.2,
        help="padding images for more accurate estimation results",
    )
    parser.add_argument(
        "--kp_mode",
        type=str,
        default="vitpose",
        help="only ViTPose is supported currently",
    )
    parser.add_argument(
        "--fitting_steps",
        nargs="+",
        type=int,
        default=[30, 50],
        help="Number of iterations for the two-stage fitting in SMPLify",
    )

    parser.add_argument("--visualize", action="store_true")
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    opt = get_parse()
    assert (
        torch.cuda.is_available()
    ), "CUDA is not available, please check your environment"
    assert os.path.exists(opt.video_path), "The video is not exists"
    os.makedirs(opt.output_path, exist_ok=True)

    FOV = 60  # follow the setting of multihmr
    device = torch.device("cuda:0")

    pipeline = Video2MotionPipeline(
        opt.model_path,
        opt.fitting_steps,
        device,
        kp_mode=opt.kp_mode,
        visualize=opt.visualize,
        pad_ratio=opt.pad_ratio,
        fov=FOV,
    )
    pipeline(opt.video_path, opt.output_path)

**Comment by robinhood256100** [comment]
问题解决了，确实是路径出了问题，我在修改python ./engine/pose_estimation/video2motion.py --video_path ./train_data/demo.mp4 --output_path ./train_data/custom_motion
这条命令的时候在输出路径之后不小心多打了一个空格，导致创建的custom_motion文件名后面有个零宽空格字符，在推理阶段代码按正常的路径访问时就找不到后面的路径了

![Image](https://github.com/user-attachments/assets/96cd391b-b526-443c-af3c-20df55cd7683)
